### ISSUE TITLE
OSX 10.11.4 (15E65)系統下抱這個錯誤

### ISSUE THREAD

**Issue by Fechin** [rinh/fekit#121]
TypeError: Cannot read property 'contentType' of undefined
    at Function.ModulePath.getContentTypeList (/usr/local/lib/node_modules/fekit/lib/compiler/module/path.js:145:40)
    at Function.ModulePath.findFileWithoutExtname (/usr/local/lib/node_modules/fekit/lib/compiler/module/path.js:167:23)
    at /usr/local/lib/node_modules/fekit/lib/middleware/fekit.js:128:33
    at Object.lookup (/usr/local/lib/node_modules/fekit/node_modules/urlrouter/lib/urlrouter.js:96:20)

**Comment by pangxin12345** [comment]
<script src='/prd/a#ver("/ver/a.js.ver").js'><script>

**Comment by pangxin12345** [comment]
`<script src='/prd/a#ver("/ver/a.js.ver").js'`

**Comment by rawbin-** [comment]
写成这样试试
<script src='/prd/a@ver("/ver/a.js.ver").js'

**Comment by Fechin** [comment]
#换成@也不行， 解决办法是在启动服务器的时候带上`--without-java`参数
```
sudo fekit server --without-java
```
