### ISSUE TITLE
node v12

### ISSUE THREAD

**Issue by greathan** [rinh/fekit#81]
node v12  报错

```
module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/fekit/node_modules/node-sass/lib/index.js:181:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

**Comment by honchy** [comment]
@greathan   
这个问题你解决了吗？ 我这里感觉好像是node-sass的版本问题，直接运行 npm install node-sass@1.2.* 也会报错的。我的node也是12 版本的。
我用node 10 可以正常安装fekit，或者npm install node-sass@2.*也可以。
应该是node 12 不能够编译1.2.*版本的node-sass导致的问题。

**Comment by greathan** [comment]
装了2.x fekit命令不报错了，但是 server 报错
/usr/local/lib/node_modules/fekit/lib/compiler/plugins/css.js:40
    return css_code.replace(RE_DOMAIN, function($0, http, domain, path) {
                    ^
TypeError: undefined is not a function
    at Object.exports.ddns (/usr/local/lib/node_modules/fekit/lib/compiler/plugins/css.js:40:21)
    at succ (/usr/local/lib/node_modules/fekit/lib/compiler/plugins/sass.js:42:27)
    at options.success (/usr/local/lib/node_modules/fekit/node_modules/node-sass/lib/index.js:163:7)

**Comment by honchy** [comment]
@greathan
我切换了node版本为0.10.28 ，fekit版本为 0.2.86 版本。 降低了两个版本，安装成功。
替换node-sass版本为2.* 你是怎么做到的

**Comment by honchy** [comment]
@greathan
我切换了node版本为0.10.28 ，fekit版本为 0.2.86 版本。 降低了两个版本，安装成功。
替换node-sass版本为2.* 你是怎么做到的

**Comment by honchy** [comment]
@greathan
我切换了node版本为0.10.28 ，fekit版本为 0.2.86 版本。 降低了两个版本，安装成功。
替换node-sass版本为2.* 你是怎么做到的

**Comment by honchy** [comment]
@greathan
我切换了node版本为0.10.28 ，fekit版本为 0.2.86 版本。 降低了两个版本，安装成功。
替换node-sass版本为2.* 你是怎么做到的

**Comment by honchy** [comment]
@greathan
我切换了node版本为0.10.28 ，fekit版本为 0.2.86 版本。 降低了两个版本，安装成功。
替换node-sass版本为2.* 你是怎么做到的

**Comment by honchy** [comment]
@greathan
我切换了node版本为0.10.28 ，fekit版本为 0.2.86 版本。 降低了两个版本，安装成功。
替换node-sass版本为2.* 你是怎么做到的

**Comment by honchy** [comment]
@greathan
我切换了node版本为0.10.28 ，fekit版本为 0.2.86 版本。 降低了两个版本，安装成功。
替换node-sass版本为2.* 你是怎么做到的

**Comment by honchy** [comment]
@greathan
我切换了node版本为0.10.28 ，fekit版本为 0.2.86 版本。 降低了两个版本，安装成功。
替换node-sass版本为2.* 你是怎么做到的

**Comment by honchy** [comment]
@greathan
我切换了node版本为0.10.28 ，fekit版本为 0.2.86 版本。 降低了两个版本，安装成功。
替换node-sass版本为2.* 你是怎么做到的

**Comment by honchy** [comment]
@greathan

我切换了node版本为0.10.28 ，fekit版本为 0.2.86 版本。 降低了两个版本，安装成功。
替换node-sass版本为2.* 你是怎么做到的

**Comment by greathan** [comment]
@honchy 在fekit目录中 npm uninstall node-sass 然后 sudo npm install node-sass@2

**Comment by rinh** [comment]
已支持 node v0.12.x
