### ISSUE TITLE
fekit 增加 对 #parse 支持

### ISSUE THREAD

**Issue by pangxin12345** [rinh/fekit#89]
Error: 找不到文件 /vm/evn/evn.vm
    at Velocity.utils.mixin.getMacro (/usr/lib/node_modules/fekit/node_modules/velocityjs/src/compile/blocks.js:98:19)
    at Velocity.<anonymous> (/usr/lib/node_modules/fekit/node_modules/velocityjs/src/compile/compile.js:79:25)
    at Array.forEach (native)
    at Object.utils.(anonymous function) [as forEach] (/usr/lib/node_modules/fekit/node_modules/velocityjs/src/utils.js:9:25)
    at Velocity.utils.mixin._render (/usr/lib/node_modules/fekit/node_modules/velocityjs/src/compile/compile.js:63:13)
    at Velocity.utils.mixin.render (/usr/lib/node_modules/fekit/node_modules/velocityjs/src/compile/compile.js:29:22)
    at _render (/usr/lib/node_modules/fekit/lib/middleware/velocity.js:60:19)
    at /usr/lib/node_modules/fekit/lib/middleware/velocity.js:100:24
    at Object.lookup (/usr/lib/node_modules/fekit/node_modules/urlrouter/lib/urlrouter.js:96:20)
    at next (/usr/lib/node_modules/fekit/node_modules/connect/lib/proto.js:190:15)

**Comment by yashiro1899** [comment]
已经支持，请更新到最新版本
